### ISSUE TITLE
Uses python3 so install command needs to be pip3 for some Linux distributions

### ISSUE THREAD

**Issue by SlySven** [hobarrera/totp-cli#17]
Using the indicated `pip` command on my Devuan 3 "Beowulf" (Debian derivative - without `systemd`) distribution fails:
```sh
user@computer:~$ pip install totp
Collecting totp
  Using cached https://files.pythonhosted.org/packages/fd/ac/a05d9dcefe55ebaeb7f35537db3fdf6d33b5f7f56237e8ee46918c9b9aa5/totp-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-XrZh7W/totp/setup.py", line 10, in <module>
        sys.version_info[0:2]
    RuntimeError: totp-cli requires python >= 3.3, but this python is 2.7
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-XrZh7W/totp/
```

`pip3 install totp` does what was wanted (and uses Python 3.x rather than Python 2.x) whilst systems are still in the switch over from the older python major version...

**Comment by WhyNotHugo** [comment]
Python 3 is over a decade old, and Python 2 reached its end of life over a year ago and is no longer supported. No distribution should still be shipping Python 2 any more really, since it doesn't even have security updates.

A very large amount of packages will fail to install with similar errors, and there's really nothing that can be done. Support for ancient Python versions is never going to happen.

Glad you figured out a workaround though, maybe this'll help out someone else having a similar issue.
